const statesData = [
  {
    id: "1",
    name: "Andhra Pradesh",
    cities: [
      { id: "1", name: "Visakhapatnam" },
      { id: "2", name: "Vijayawada" },
      { id: "3", name: "Guntur" },
      { id: "4", name: "Nellore" },
      { id: "5", name: "Kurnool" },
    ],
  },
  {
    id: "2",
    name: "Arunachal Pradesh",
    cities: [
      { id: "6", name: "Itanagar" },
      { id: "7", name: "Tawang" },
      { id: "8", name: "Ziro" },
      { id: "9", name: "Pasighat" },
      { id: "10", name: "Bomdila" },
    ],
  },
  {
    id: "3",
    name: "Assam",
    cities: [
      { id: "11", name: "Guwahati" },
      { id: "12", name: "Silchar" },
      { id: "13", name: "Dibrugarh" },
      { id: "14", name: "Jorhat" },
      { id: "15", name: "Tezpur" },
    ],
  },
  {
    id: "4",
    name: "Bihar",
    cities: [
      { id: "16", name: "Patna" },
      { id: "17", name: "Gaya" },
      { id: "18", name: "Bhagalpur" },
      { id: "19", name: "Muzaffarpur" },
      { id: "20", name: "Darbhanga" },
    ],
  },
  {
    id: "5",
    name: "Chhattisgarh",
    cities: [
      { id: "21", name: "Raipur" },
      { id: "22", name: "Bilaspur" },
      { id: "23", name: "Durg" },
      { id: "24", name: "Korba" },
      { id: "25", name: "Jagdalpur" },
    ],
  },
  {
    id: "6",
    name: "Goa",
    cities: [
      { id: "26", name: "Panaji" },
      { id: "27", name: "Margao" },
      { id: "28", name: "Vasco da Gama" },
      { id: "29", name: "Mapusa" },
      { id: "30", name: "Ponda" },
    ],
  },
  {
    id: "7",
    name: "Gujarat",
    cities: [
      { id: "31", name: "Ahmedabad" },
      { id: "32", name: "Surat" },
      { id: "33", name: "Vadodara" },
      { id: "34", name: "Rajkot" },
      { id: "35", name: "Bhavnagar" },
    ],
  },
  {
    id: 8,
    name: "Haryana",
    cities: [
      { id: "36", name: "Gurugram" },
      { id: "37", name: "Faridabad" },
      { id: "38", name: "Panipat" },
      { id: "39", name: "Ambala" },
      { id: "40", name: "Rohtak" },
    ],
  },
  {
    id: "9",
    name: "Himachal Pradesh",
    cities: [
      { id: "41", name: "Shimla" },
      { id: "42", name: "Manali" },
      { id: "43", name: "Dharamshala" },
      { id: "44", name: "Kullu" },
      { id: "45", name: "Solan" },
    ],
  },
  {
    id: "10",
    name: "Jharkhand",
    cities: [
      { id: "46", name: "Ranchi" },
      { id: "47", name: "Jamshedpur" },
      { id: "48", name: "Dhanbad" },
      { id: "49", name: "Bokaro" },
      { id: "50", name: "Deoghar" },
    ],
  },
  {
    id: "11",
    name: "Karnataka",
    cities: [
      { id: "51", name: "Bangalore" },
      { id: "52", name: "Mysore" },
      { id: "53", name: "Mangalore" },
      { id: "54", name: "Hubli" },
      { id: "55", name: "Belgaum" },
    ],
  },
  {
    id: "12",
    name: "Kerala",
    cities: [
      { id: "56", name: "Thiruvananthapuram" },
      { id: "57", name: "Kochi" },
      { id: "58", name: "Kozhikode" },
      { id: "59", name: "Thrissur" },
      { id: "60", name: "Kollam" },
    ],
  },
  {
    id: "13",
    name: "Madhya Pradesh",
    cities: [
      { id: "61", name: "Indore" },
      { id: "62", name: "Bhopal" },
      { id: "63", name: "Gwalior" },
      { id: "64", name: "Jabalpur" },
      { id: "65", name: "Ujjain" },
    ],
  },
  {
    id: "14",
    name: "Maharashtra",
    cities: [
      { id: "66", name: "Mumbai" },
      { id: "67", name: "Pune" },
      { id: "68", name: "Nagpur" },
      { id: "69", name: "Nashik" },
      { id: "70", name: "Thane" },
    ],
  },
  {
    id: "15",
    name: "Manipur",
    cities: [
      { id: "71", name: "Imphal" },
      { id: "72", name: "Thoubal" },
      { id: "73", name: "Kakching" },
      { id: "74", name: "Ukhrul" },
      { id: "75", name: "Bishnupur" },
    ],
  },
  {
    id: "16",
    name: "Meghalaya",
    cities: [
      { id: "76", name: "Shillong" },
      { id: "77", name: "Tura" },
      { id: "78", name: "Nongpoh" },
      { id: "79", name: "Jowai" },
      { id: "80", name: "Baghmara" },
    ],
  },
  {
    id: "17",
    name: "Mizoram",
    cities: [
      { id: "81", name: "Aizawl" },
      { id: "82", name: "Lunglei" },
      { id: "83", name: "Serchhip" },
      { id: "84", name: "Champhai" },
      { id: "85", name: "Kolasib" },
    ],
  },
  {
    id: "18",
    name: "Nagaland",
    cities: [
      { id: "86", name: "Kohima" },
      { id: "87", name: "Dimapur" },
      { id: "88", name: "Mokokchung" },
      { id: "89", name: "Tuensang" },
      { id: "90", name: "Wokha" },
    ],
  },
  {
    id: "19",
    name: "Odisha",
    cities: [
      { id: "91", name: "Bhubaneswar" },
      { id: "92", name: "Cuttack" },
      { id: "93", name: "Rourkela" },
      { id: "94", name: "Sambalpur" },
      { id: "95", name: "Berhampur" },
    ],
  },
  {
    id: "20",
    name: "Punjab",
    cities: [
      { id: "96", name: "Ludhiana" },
      { id: "97", name: "Amritsar" },
      { id: "98", name: "Jalandhar" },
      { id: "99", name: "Patiala" },
      { id: "100", name: "Bathinda" },
    ],
  },
  {
    id: "21",
    name: "Rajasthan",
    cities: [
      { id: "101", name: "Jaipur" },
      { id: "102", name: "Jodhpur" },
      { id: "103", name: "Udaipur" },
      { id: "104", name: "Kota" },
      { id: "105", name: "Ajmer" },
    ],
  },
  {
    id: "22",
    name: "Sikkim",
    cities: [
      { id: "106", name: "Gangtok" },
      { id: "107", name: "Namchi" },
      { id: "108", name: "Mangan" },
      { id: "109", name: "Gyalshing" },
      { id: "110", name: "Rangpo" },
    ],
  },
  {
    id: "23",
    name: "Tamil Nadu",
    cities: [
      { id: "111", name: "Chennai" },
      { id: "112", name: "Coimbatore" },
      { id: "113", name: "Madurai" },
      { id: "114", name: "Tiruchirappalli" },
      { id: "115", name: "Salem" },
    ],
  },
  {
    id: "24",
    name: "Telangana",
    cities: [
      { id: "116", name: "Hyderabad" },
      { id: "117", name: "Warangal" },
      { id: "118", name: "Nizamabad" },
      { id: "119", name: "Karimnagar" },
      { id: "120", name: "Khammam" },
    ],
  },
  {
    id: "25",
    name: "Tripura",
    cities: [
      { id: "121", name: "Agartala" },
      { id: "122", name: "Udaipur" },
      { id: "123", name: "Dharmanagar" },
      { id: "124", name: "Belonia" },
      { id: "125", name: "Kailashahar" },
    ],
  },
  {
    id: "26",
    name: "Uttar Pradesh",
    cities: [
      { id: "126", name: "Lucknow" },
      { id: "127", name: "Kanpur" },
      { id: "128", name: "Ghaziabad" },
      { id: "129", name: "Agra" },
      { id: "130", name: "Meerut" },
    ],
  },
  {
    id: "27",
    name: "Uttarakhand",
    cities: [
      { id: "131", name: "Dehradun" },
      { id: "132", name: "Haridwar" },
      { id: "133", name: "Rishikesh" },
      { id: "134", name: "Nainital" },
      { id: "135", name: "Haldwani" },
    ],
  },
  {
    id: "28",
    name: "West Bengal",
    cities: [
      { id: "136", name: "Kolkata" },
      { id: "137", name: "Asansol" },
      { id: "138", name: "Durgapur" },
      { id: "139", name: "Siliguri" },
      { id: "140", name: "Howrah" },
    ],
  },
];

export { statesData };
